apiVersion: v1
kind: Secret
metadata:
  name: minio-license
  namespace: local-lakehouse-dev
type: Opaque
stringData:
  minio.license: "ZXlKaGJHY2lPaUpGVXpNNE5DSXNJblI1Y0NJNklrcFhWQ0o5LmV5SmhhV1FpT2pBc0ltTmhjQ0k2TUN3aWFXRjBJam94TGpjMk56azFOek0wTkRJMk9UWTROamt5T0dVNUxDSnBjM01pT2lKemRXSnVaWFJBYldsdUxtbHZJaXdpYkdsa0lqb2lNbUpsWW1JNVpXSXRPR1k1T0MwME1ETXdMV0U1Wm1RdFpXWmlaakpoTldZd016TXhJaXdpYjNKbklqb2lJaXdpY0d4aGJpSTZJa1pTUlVVaUxDSnpkV0lpT2lKbmIyeGtiV0ZzWTI5dE5ETkFaMjFoYVd3dVkyOXRJaXdpZEhKcFlXd2lPbVpoYkhObGZRLmI1azdMX0tVZjlZMFJoVFVILVJLeENJVHJUTHZlcDA3TkZHXzFTdzlxNkl2MDVudDh0R2pxTTV4dWpQd1I2N2xCc0FpbGxfUEh1ZUEwcGVvVnJjSUdIRGNUX3NyZFRfMHJEWjF6UWN3aGJYRkJYU2x6dzBEYThraTVTREJabnFT"
