---
# Source: hue/templates/configmap-hue.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hue-config
data:
  hue-ini: |
    [desktop]

    [[database]]
    engine=postgresql_psycopg2
    host=postgres-hue
    port=5432
    user=hue
    password=hue
    name=hue

    [aws]
    [[aws_accounts]]
    [[[default]]]
    access_key_id=
    secret_access_key=
    region=us-east-1

    [notebook]
    [[interpreters]]
        [[[postgresql]]]
      name = postgresql
      interface=sqlalchemy
      options='{"url": "postgresql://hue:hue@postgres-hue:5432/hue"}'
