---
# Source: hue/templates/configmap-hive.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-config
data:
  hive-site: |
    <?xml version="1.0"?>
    <?xml-stylesheet type="text/xsl" href="configuration.xsl"?>

    <configuration>

    <!--
    <property>
      <name>hive.support.concurrency</name>
      <value>false</value>
      <description>Whether hive supports concurrency or not. A zookeeper instance must be up and running for the default hive lock manager to support read-write locks.</description>
    </property>
    -->

    </configuration>
