---
# Source: trino/templates/service-worker.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-name-trino-worker
  namespace: default
  labels:
    helm.sh/chart: trino-1.42.2
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "480"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: worker
  annotations:
    {}
spec:
  clusterIP: None
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/component: worker
