objectStore:
   name: minio-object-store # name of the AIStor Server
   pools:
   - name: pool-0
     servers: 1 # Number of servers/pods to deploy (1 for free licenses, more for paid licenses)
     volumesPerServer: 1 # Number of Persistent Volumes per Server/Pod
     size: 2Gi # Size of each PV
#    storageClassName: directpv-min-io # Storage Class assigned to each PV
   services:
      minio:
         serviceType: NodePort
         nodePort: 31000 # Select an available NodePort in the supported range of 30000-32767
      console:
         serviceType: NodePort
         nodePort: 31200 # Select an available NodePort in the supported range of 30000-32767
  
   certificates:
      # Enable automatic Kubernetes based `certificate generation and signing <https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster>`__
      # With disableAutoCert: false (default), AIStor will create a Certificate resource and a corresponding CertificateSigningRequest (CSR) for each server, and the Kubernetes controller will automatically sign the CSRs using the cluster's CA. This is the recommended option for production environments as it provides secure, automatically managed certificates.
      # With disableAutoCert: true, AIStor will not create any Certificate resources
      disableAutoCert: true
