apiVersion: apps/v1
kind: Deployment
metadata:
  name: hue-deployment
  labels:
    app: hue
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hue
  template:
    metadata:
      labels:
        app: hue
    spec:
      containers:
      - name: hue
        image: gethue/hue:latest
        ports:
        - containerPort: 8888
          name: hue-port


--- # Hue service
# The blueprint of our Hue internal service in k8s cluster which will allow the requests exchange between the pods
# LoadBalancer service for testing purposes currently
apiVersion: v1
kind: Service
metadata:
  name: hue-service
spec:
  selector:
    app: hue
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: hue-port
    nodePort: 30080
