service:
  type: NodePort
  port: 8088
  annotations: {}
    # cloud.google.com/load-balancer-type: "Internal"
  loadBalancerIP: ~
  nodePort:
    # -- (int)
    http: 31800
  
configOverrides:
  secret: |
    SECRET_KEY = 'zCUyFvnM9NT2W8awcgUwhKbiOGZ+uFAHncFgMO/cBnLHk0m/hgBeBtQt'

bootstrapScript: |
  #!/bin/bash
  uv pip install .[postgres] .[trino] &&\
  if [ ! -f ~/bootstrap ]; then echo "Running Superset with uid {{ .Values.runAsUser }}" > ~/bootstrap; fi