apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-deployment
  labels:
    app: trino
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trino
  template:
    metadata:
      labels:
        app: trino
    spec:
      containers:
      - name: trino-engine
        image: trinodb/trino:479
        ports:
        - containerPort: 8080
          name: trino-port




--- # Trino service
# The blueprint of our Trino internal service in k8s cluster which will allow the requests exchange between the pods
# LoadBalancer service for testing purposes currently
apiVersion: v1
kind: Service
metadata:
  name: trino-service
spec:
  selector:
    app: trino
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: trino-port
    nodePort: 30081
