test_dbt:
  target: dev
  outputs:
    dev:
      type: trino
      method: none
      user: trino
      host: trino-engine 
      port: 8080
      database: minio-warehouse
      schema: sales_schema
      threads: 4