connector.name=iceberg
# Utilisation de Postgres comme catalogue pour Iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=http://minio-aistor-server:9008/_iceberg
iceberg.rest-catalog.warehouse=silver
iceberg.rest-catalog.security=SIGV4
iceberg.rest-catalog.vended-credentials-enabled=true
iceberg.unique-table-location=true
iceberg.rest-catalog.signing-name=s3tables
iceberg.rest-catalog.view-endpoints-enabled=true
iceberg.add-files-procedure.enabled=true
fs.native-s3.enabled=true
s3.region=local
s3.aws-access-key=airflow
s3.aws-secret-key=miniopasswd
s3.endpoint=http://minio-aistor-server:9008
s3.path-style-access=true
fs.hadoop.enabled=false