# This .toml file is a blueprint.
# Feel free to tweak it at your convenience.
# Ensure to apply the modifications to the other affected variables.

[DAG]
# The unique identifier of your DAG. This must be unique across your entire Airflow environment, as it is the primary key in the Airflow database.
dag_id = "Local_data_lakehouse_ELT_pipeline"
# A slight summary of what the ELT process does. It appears in the "Description" column of the Airflow UI.
dag_description = "A DAG for processing data in a local data lakehouse."
# The name of the person or team responsible for the DAG. This is used in the Airflow UI to filter DAGs.
owner = "MCA_data_engineering_team"
# The number of times a task will attempt to run again if it fails.
retries_number = 5
# A boolean (true/false) that determines how Airflow handles "missed" runs.
catchup = false
# The date and time when the DAG should start being eligible for scheduling. Use the "YYYY-MM-DD" format (Example: 2024-12-21).
start_date = "2026-01-01"
# Defines how often the DAG runs (e.g. a preset airflow expression like "@daily", a Cron expression like 0 0 * * *).
schedule = "@daily"


[STORAGE]
# Unique ID for the "Amazon Web Services" Connection configured through Airflow UI. This Connection allows the communication between duckdb engine and MinIO S3 API.
# Please ensure the value of "airflow_aws_connection_id" variable is the same as the ID of the "Amazon Web Services" Connection configured through Airflow UI.
airflow_aws_connection_id = "minio_conn"
# Name of the MinIO Bronze Bucket.
# Please ensure the value of "airflow_aws_connection_id" variable is the same as the value of MINIO_BRONZE_BUCKET_NAME variable defined in the "./minio-volumes/minio_variables.env" file .
bronze_bucket_name = "bronze"
# Name of the MinIO Silver Bucket.
# Please ensure the value of "airflow_aws_connection_id" variable is the same as the value of MINIO_SILVER_BUCKET_NAME variable defined in the "./minio-volumes/minio_variables.env" file .
silver_bucket_name = "silver"
# Name of the MinIO Gold Bucket.
# Please ensure the value of "airflow_aws_connection_id" variable is the same as the value of MINIO_GOLD_BUCKET_NAME variable defined in the "./minio-volumes/minio_variables.env" file .
gold_bucket_name = "gold"
# Compression mode for parquet files written in the Silver Bucket.
silver_parquet_files_compression_mode = "SNAPPY"
# Compression mode for parquet files written in the Gold Bucket.
gold_parquet_files_compression_mode = "SNAPPY"
# MinIO API Port. Not be confused with MinIO Console port.
# Please ensure the value of "minio_s3_api_port" variable is the same as the value of MINIO_API_PORT variable defined in the ".env" file at the root path of the project directory.
minio_s3_api_port = 9008
# This defines how the URL is constructed to find your buckets. 
#   - vhost (Virtual Hosted-Style): The bucket name is in the subdomain (e.g., bucket.s3.amazonaws.com). This is the AWS S3 standard.
#   - path (Path-Style): The bucket name follows the domain (e.g., minio:9000/bucket). This is the standard for MinIO or older S3 implementations.
duckdb_s3_url_style_config_param = "path"
# A string ("true"/"false"). If you are using standard AWS S3, this is usually "true". For local development with MinIO (without a proxy), it is usually "false".
duckdb_s3_use_ssl_config_param = "false"

[TASKS]
# A unique ID for the "File (path)" Connection configured through Aitflow UI. This Connection allows the Airflow fileSensor to check whether raw JSON files are available in the local directory.
fileSensor_connection_id = "fs_conn"
# Path to the local directory where raw JSON files are dumped before extraction to MinIO Bronze Bucket.
# Please ensure the value of "source_dir" variable is the same as the "Path" variable defined in the "File (path)" Connection configured through Airflow UI.
source_dir = "/opt/airflow/local-data"
# The time (in seconds) that the sensor waits between each attempt to check if the file exists. 
checking_raw_json_files_existence_poke_interval = 10
# The total amount of time (in seconds) that the sensor is allowed to keep "poking" before it gives up.
checking_raw_json_files_existence_timeout = 30
# JSON filename pattern to check to ensure raw JSON files are available locally.
checking_raw_json_files_existence_file_pattern = "sales*"
# Base currency to use for currency conversion purposes for Gold Bucket data.
gold_bucket_base_currency = "EUR"