# Chart.yaml

apiVersion: v2
name: local-lakehouse-stack
description: A Helm chart for deploying the Local Lakehouse Stack
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  # Local charts
  - name: trino
    version: "1.42.2"
    repository: "file://charts/trino"
    condition: trino.enabled
  
  - name: hue-modified
    version: "1.0.3"
    repository: "file://charts/hue-modified"
    condition: hue-modified.enabled

  - name: aistor-operator
    version: "5.9.0"
    repository: "file://charts/aistor-operator"
    condition: aistor-operator.enabled

  - name: aistor-objectstore
    version: "1.0.16"
    repository: "file://charts/aistor-objectstore"
    condition: aistor-objectstore.enabled

  - name: superset
    version: "0.21.1"
    repository: "file://charts/superset"
    condition: superset.enabled