---
# Source: aistor-objectstore-operator/templates/deployment-operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminjob-operator
  namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      aistor.min.io/name: adminjob-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        aistor.min.io/name: adminjob-operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: aistor.min.io/name
                operator: In
                values:
                - adminjob-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - adminjob
        - -license
        - /tmp/license/minio.license
        env:
        - name: MINIO_OPERATOR_DEPLOYMENT_NAME
          value: adminjob-operator
        image: "quay.io/minio/aistor/operator:RELEASE.2025-08-19T17-53-00Z"
        name: controller
        resources:
          requests:
            cpu: 200m
            ephemeral-storage: 100Mi
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp/license
          name: minio-license
      dnsPolicy: ClusterFirst
      serviceAccountName: aistor-adminjob
      volumes:
      - name: minio-license
        secret:
          defaultMode: 444
          optional: true
          secretName: minio-license
---
# Source: aistor-objectstore-operator/templates/deployment-operator.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-store-operator
  namespace: "default"
spec:
  replicas: 1
  selector:
    matchLabels:
      aistor.min.io/name: object-store-operator
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        aistor.min.io/name: object-store-operator
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: aistor.min.io/name
                operator: In
                values:
                - object-store-operator
            topologyKey: kubernetes.io/hostname
      containers:
      - args:
        - controller
        - -license
        - /tmp/license/minio.license
        env:
        - name: MINIO_OPERATOR_DEPLOYMENT_NAME
          value: object-store-operator
        - name: OPERATOR_STS_ENABLED
          value: "off"
        image: "quay.io/minio/aistor/operator:RELEASE.2025-08-19T17-53-00Z"
        name: controller
        resources:
          requests:
            cpu: 200m
            ephemeral-storage: 100Mi
            memory: 256Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsGroup: 1000
          runAsNonRoot: true
          runAsUser: 1000
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /tmp/license
          name: minio-license
        - name: minio-token-volume
          mountPath: /var/run/secrets/sts.min.io
          readOnly: true
      dnsPolicy: ClusterFirst
      serviceAccountName: aistor-object-store
      volumes:
      - name: minio-license
        secret:
          defaultMode: 444
          optional: true
          secretName: minio-license
      - name: minio-token-volume
        projected:
          sources:
          - serviceAccountToken:
              path: token
              audience: sts.min.io
              expirationSeconds: 3600
