# Trino subchart values
trino:
  enabled: true

  image:
    tag: "479"

  server:
    workers: 2

  catalogs:
    minio_warehouse: |
      connector.name=iceberg
      iceberg.catalog.type=rest
      iceberg.rest-catalog.uri=http://minio:80/_iceberg
      iceberg.rest-catalog.warehouse=test-warehouse
      iceberg.rest-catalog.security=SIGV4
      iceberg.rest-catalog.vended-credentials-enabled=true
      iceberg.unique-table-location=true
      iceberg.rest-catalog.signing-name=s3tables
      iceberg.rest-catalog.view-endpoints-enabled=true
      iceberg.add-files-procedure.enabled=true
      iceberg.expire-snapshots.min-retention=5d
      iceberg.remove-orphan-files.min-retention=5d
      fs.native-s3.enabled=true
      s3.region=local
      s3.aws-access-key=minio
      s3.aws-secret-key=minio123
      s3.endpoint=http://minio:80
      s3.path-style-access=true
      fs.hadoop.enabled=false

  # Allowing the access to Trino web dashboard through 31205 port
  service:
    annotations: {}
    type: NodePort
    nodePort: "31205"


# hue-modified subchart values
hue-modified:
  enabled: true

  image:
    registry: "gethue"
    tag: "latest"
    pullPolicy: "Always"

  hue:
    replicas: 2
    database:
      create: true
      persist: true
      engine: "postgresql_psycopg2"
      host: "postgres-hue"
      port: 5432
      user: "hue"
      password: "hue"
      #password_script=echo ${DATABASE_PASSWORD}
      name: "hue"
      storageName: "microk8s-hostpath"
    interpreters: |
      [[[trino]]]
        name=Trino
        interface=trino
        options='{"url": "http://trino:8080/minio_warehouse/"}'
    ini: |
      [desktop]
      secret_key=hue123
      app_blacklist=hive,impala,security,search,pig,oozie,jobbrowser, hbase
      django_debug_mode=false
      gunicorn_work_class=sync
      enable_prometheus=true

      [[storage_connectors]]
        [[[minio_dev]]]
          provider=generic
          auth_type=key
          #Endpoint is built like this: http://{minio objectstore service name}:{service port} (use https if enabled for minio)
          endpoint=http://minio:80
          access_key_id=minio
          secret_key=minio123
          options={"signature_version": "s3v4"}

      [[task_server]]
      enabled=false
      broker_url=redis://redis:6379/0
      result_cache='{"BACKEND": "django_redis.cache.RedisCache", "LOCATION": "redis://redis:6379/0", "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},"KEY_PREFIX": "queries"}'
      celery_result_backend=redis://redis:6379/0

aistor-operator:
  enabled: true
  license: "eyJhbGciOiJFUzM4NCIsInR5cCI6IkpXVCJ9.eyJhaWQiOjAsImNhcCI6MCwiaWF0IjoxLjc2Nzk1NzM0NDI2OTY4NjkyOGU5LCJpc3MiOiJzdWJuZXRAbWluLmlvIiwibGlkIjoiMmJlYmI5ZWItOGY5OC00MDMwLWE5ZmQtZWZiZjJhNWYwMzMxIiwib3JnIjoiIiwicGxhbiI6IkZSRUUiLCJzdWIiOiJnb2xkbWFsY29tNDNAZ21haWwuY29tIiwidHJpYWwiOmZhbHNlfQ.b5k7L_KUf9Y0RhTUH-RKxCITrTLvep07NFG_1Sw9q6Iv05nt8tGjqM5xujPwR67lBsAill_PHueA0peoVrcIGHDcT_srdT_0rDZ1zQcwhbXFBXSlzw0Da8ki5SDBZnqS"

aistor-objectstore:
  enabled: true

  objectStore:
    name: minio-object-store # name of the AIStor Server
    pools:
    - name: pool-0
      servers: 1 # Number of servers/pods to deploy (1 for free licenses, more for paid licenses)
      volumesPerServer: 1 # Number of Persistent Volumes per Server/Pod
      size: 2Gi # Size of each PV
  #    storageClassName: directpv-min-io # Storage Class assigned to each PV
    services:
        minio:
          serviceType: NodePort
          nodePort: 31000 # Select an available NodePort in the supported range of 30000-32767
        console:
          serviceType: NodePort
          nodePort: 31200 # Select an available NodePort in the supported range of 30000-32767
    
    certificates:
        # Enable automatic Kubernetes based `certificate generation and signing <https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster>`__
        # With disableAutoCert: false (default), AIStor will create a Certificate resource and a corresponding CertificateSigningRequest (CSR) for each server, and the Kubernetes controller will automatically sign the CSRs using the cluster's CA. This is the recommended option for production environments as it provides secure, automatically managed certificates.
        # With disableAutoCert: true, AIStor will not create any Certificate resources
        disableAutoCert: true


